name: Deploy Website

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t forge-reality .

      - name: verify Docker images
        run: |
          docker images

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Website Files
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy Website
        uses: actions/deploy-pages@v4
